### ISSUE TITLE
StructRNA of type VectorFont has been removed

### ISSUE THREAD

**Issue by leifniem** [Kirpal/Keyboard-Layout-Editor-for-Blender#52]
I encountered this issue when trying to import a DSA Layout in 2.82 with the 3.0 plugin.

```Traceback (most recent call last):
  File "/Volumes/Files/Users/leif/Library/Application Support/Blender/2.82/scripts/addons/keyboard-layout-editor-for-blender/__init__.py", line 29, in execute
    import_keyboard.read(self.filepath)
  File "/Volumes/Files/Users/leif/Library/Application Support/Blender/2.82/scripts/addons/keyboard-layout-editor-for-blender/import_keyboard.py", line 674, in read
    new_obj_tl)
  File "/Volumes/Files/Users/leif/Library/Application Support/Blender/2.82/scripts/addons/keyboard-layout-editor-for-blender/add_label.py", line 60, in add
    new_label.data.font = font
ReferenceError: StructRNA of type VectorFont has been removed

location: <unknown location>:-1

```

Sorry if this is a tad vague, i can try providing more data if it helps.

**Comment by AlecVercruysse** [comment]
I have the same issue when opening the blender scene file and then attempting to import the default Leopold FC660m layout. I'm using blender 2.81

**Comment by leifniem** [comment]
Seems this is fixable by restarting Blender. At least it did work for me just now
