### ISSUE TITLE
Add error handling for invalid key colors

### ISSUE THREAD

**Issue by SivertGullbergHansen** [Kirpal/Keyboard-Layout-Editor-for-Blender#70]
Hello! 
I'm not able to import the .json file that I download from http://www.keyboard-layout-editor.com/
I've tried reading how to use this three times now and I hope I'm not making a simple mistake.
I'm running

- Blender version 2.80 

- Python version 3.7.0

- KLE-plugin version 3.1

I also opened the blender scene you recommended _template.blend_ before importing.

Here's the error I receive upon importing the .json-file:
```
Traceback (most recent call last):
  File "C:\Users\xx\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\Keyboard-Layout-Editor-for-Blender-master\__init__.py", line 30, in execute
    return import_keyboard.load_json(self, self.filepath)
  File "C:\Users\xx\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\Keyboard-Layout-Editor-for-Blender-master\import_keyboard.py", line 373, in load_json
    read(filepath)
  File "C:\Users\xx\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\Keyboard-Layout-Editor-for-Blender-master\import_keyboard.py", line 236, in read
    key_obj)
  File "C:\Users\xx\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\Keyboard-Layout-Editor-for-Blender-master\labels.py", line 217, in add
    curve = add_text(key_label.text, label_size, font, label_position, box)
  File "C:\Users\xx\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\Keyboard-Layout-Editor-for-Blender-master\labels.py", line 165, in add_text
    new_label.data.font = font
ReferenceError: StructRNA of type VectorFont has been removed

location: <unknown location>:-1
```

By the way, the first thing that threw me off was that under "File" I cannot find "User Preferences". I had to go through Edit > Preferences in order to find my Add-ons tab. Just thought I'd point it out and perhaps that's a clue to why importing doesn't work? I know that previous versions of blender had this but I believe they changed this with the 2.80 update.

I could try rolling back to an earlier version of blender, but I hope I do not have to do so :)

**Comment by Kirpal** [comment]
Please post the layout you're using

**Comment by SivertGullbergHansen** [comment]
```
[
  {
    "background": {
      "name": "Aluminium brushed",
      "style": "background-image: url('/bg/metal/aluminum_texture1642.jpg');"
    }
  },
  [
    {
      "c": "#ffcccc",
      "t": "#d19b9b",
      "p": "OEM",
      "sm": "cherry",
      "sb": "gateron",
      "st": "KS-3-Tea"
    },
    "¬\n`",
    "!\n1",
    "\"\n2",
    "£\n3",
    "$\n4",
    "%\n5",
    "^\n6",
    "&\n7",
    "*\n8",
    "(\n9",
    ")\n0",
    "_\n-",
    "+\n=",
    {
      "w": 2
    },
    "Backspace"
  ],
  [
    {
      "w": 1.5
    },
    "Tab",
    "Q",
    "W",
    "E",
    "R",
    "T",
    "Y",
    "U",
    "I",
    "O",
    "P",
    "{\n[",
    "}\n]",
    {
      "x": 0.25,
      "w": 1.25,
      "h": 2,
      "w2": 1.5,
      "h2": 1,
      "x2": -0.25
    },
    "Enter"
  ],
  [
    {
      "w": 1.75
    },
    "Caps Lock",
    "A",
    "S",
    "D",
    "F",
    "G",
    "H",
    "J",
    "K",
    "L",
    ":\n;",
    "@\n'",
    "~\n#"
  ],
  [
    {
      "w": 1.25
    },
    "Shift",
    "|\n\\",
    "Z",
    "X",
    "C",
    "V",
    "B",
    "N",
    "M",
    "<\n,",
    ">\n.",
    "?\n/",
    {
      "w": 2.75
    },
    "Shift"
  ],
  [
    {
      "w": 1.25
    },
    "Ctrl",
    {
      "w": 1.25
    },
    "Win",
    {
      "w": 1.25
    },
    "Alt",
    {
      "a": 7,
      "w": 6.25
    },
    "",
    {
      "a": 4,
      "w": 1.25
    },
    "AltGr",
    {
      "w": 1.25
    },
    "Win",
    {
      "w": 1.25
    },
    "Menu",
    {
      "w": 1.25
    },
    "Ctrl"
  ]
]
```

**Comment by Kirpal** [comment]
Try using a blank blender file, looks like this happens when you use template.blend

**Comment by SivertGullbergHansen** [comment]
Wow that's crazy, before posting this issue I did use an empty blender file.
Here's the steps of what I did just now:
Opened blender, File > Import > KLE Raw Data (.json), select the keyboard layout, Voilà!

Thanks a lot!

**Comment by SivertGullbergHansen** [comment]
I ran into the same problem when using a different color-scheme;
Here's the error-code:
```
Traceback (most recent call last):
  File "C:\Users\saive\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\Keyboard-Layout-Editor-for-Blender-master\__init__.py", line 30, in execute
    return import_keyboard.load_json(self, self.filepath)
  File "C:\Users\saive\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\Keyboard-Layout-Editor-for-Blender-master\import_keyboard.py", line 373, in load_json
    read(filepath)
  File "C:\Users\saive\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\Keyboard-Layout-Editor-for-Blender-master\import_keyboard.py", line 143, in read
    make_key_material(key.color)
  File "C:\Users\saive\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\Keyboard-Layout-Editor-for-Blender-master\materials.py", line 39, in make_key_material
    diffuseBSDF.inputs["Color"].default_value = hex2rgb(color)
  File "C:\Users\saive\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\Keyboard-Layout-Editor-for-Blender-master\helpers.py", line 63, in hex2rgb
    r = int(str(hex[0:2]), 16)
ValueError: invalid literal for int() with base 16: 'GO'

location: <unknown location>:-1
```

And the layout I used
```
[
  [
    {
      "c": "#fff1ff",
      "t": "#38302E",
      "g": true,
      "p": "OEM"
    },
    "~\n`",
    "!\n1",
    {
      "c": "#e9feff"
    },
    "@\n2",
    {
      "c": "#d2ffe8"
    },
    "#\n3",
    {
      "c": "#ddfdd4"
    },
    "$\n4",
    {
      "c": "#feefd8"
    },
    "%\n5",
    {
      "c": "Got it! We use cookies to personalise content and ads, to provide social media features and to analyse our traffic. We also share information about your use of our site with our social media, advertising and analytics partners. See details  IMAGECOLORPICKER.COM ...pick your color online Color Picker Click on the image to get the html codes..  Use the online image color picker right to select a color and get the HTML Color Code of this pixel. Also you get the HEX color code value, RGB value and HSV value. You can put a picture url in the textbox below or upload your own image. (for example an screenshot of your desktop). Or use an website url, you will see a thumbnail on the right side.  HTML/HEX code:\t#f4c4d4\t RGB code:\trgb(244, 196, 212)\t show more Dominant color:    Palette:   Upload your image We think data protection is important! No data is sent. The magic happens in your browser.  - or - Use this box to get the HTML color code from a website. Without installing an Extension.  Take website Use this box to get the HTML color code from a picture via his url:  Take image Scan real-life surfaces to find their digital color values. Scan real-life surfaces to find their digital color values. This website is financed by advertisements. You use a blocker. We understand that you don't want to see advertisements. Operating and maintaining this site costs us money. We are very happy about any support! Donate with PayPal button Love imagecolorpicker.com?  Give our service 5 stars.   Copyright 2020 - ImageColorPicker.com | V: color-picker-244 | Privacy Policy | Imprint"
    },
    "^\n6",
    "&\n7",
    "*\n8",
    {
      "c": "#feefd8"
    },
    "(\n9",
    {
      "c": "#ddfdd4"
    },
    ")\n0",
    {
      "c": "#d2ffe8"
    },
    "_\n-",
    {
      "c": "#e9feff"
    },
    "+\n=",
    {
      "c": "#fff1ff",
      "w": 2
    },
    "Backspace"
  ],
  [
    {
      "c": "#fcfcfc",
      "w": 1.5
    },
    "Tab",
    {
      "c": "#fff1ff"
    },
    "Q",
    {
      "c": "#e9feff"
    },
    "W",
    {
      "c": "#d2ffe8"
    },
    "E",
    {
      "c": "#ddfdd4"
    },
    "R",
    {
      "c": "#feefd8"
    },
    "T",
    {
      "c": "Got it! We use cookies to personalise content and ads, to provide social media features and to analyse our traffic. We also share information about your use of our site with our social media, advertising and analytics partners. See details  IMAGECOLORPICKER.COM ...pick your color online Color Picker Click on the image to get the html codes..  Use the online image color picker right to select a color and get the HTML Color Code of this pixel. Also you get the HEX color code value, RGB value and HSV value. You can put a picture url in the textbox below or upload your own image. (for example an screenshot of your desktop). Or use an website url, you will see a thumbnail on the right side.  HTML/HEX code:\t#f4c4d4\t RGB code:\trgb(244, 196, 212)\t show more Dominant color:    Palette:   Upload your image We think data protection is important! No data is sent. The magic happens in your browser.  - or - Use this box to get the HTML color code from a website. Without installing an Extension.  Take website Use this box to get the HTML color code from a picture via his url:  Take image Scan real-life surfaces to find their digital color values. Scan real-life surfaces to find their digital color values. This website is financed by advertisements. You use a blocker. We understand that you don't want to see advertisements. Operating and maintaining this site costs us money. We are very happy about any support! Donate with PayPal button Love imagecolorpicker.com?  Give our service 5 stars.   Copyright 2020 - ImageColorPicker.com | V: color-picker-244 | Privacy Policy | Imprint"
    },
    "Y",
    "U",
    {
      "c": "#feefd8"
    },
    "I",
    {
      "c": "#ddfdd4"
    },
    "O",
    {
      "c": "#d2ffe8"
    },
    "P",
    {
      "c": "#e9feff"
    },
    "{\n[",
    {
      "c": "#fff1ff"
    },
    "}\n]",
    {
      "c": "#fcfcfc",
      "w": 1.5
    },
    "|\n\\"
  ],
  [
    {
      "w": 1.75
    },
    "Caps Lock",
    {
      "c": "#fff1ff"
    },
    "A",
    {
      "c": "#e9feff"
    },
    "S",
    {
      "c": "#d2ffe8"
    },
    "D",
    {
      "c": "#ddfdd4"
    },
    "F",
    {
      "c": "#feefd8"
    },
    "G",
    {
      "c": "Got it! We use cookies to personalise content and ads, to provide social media features and to analyse our traffic. We also share information about your use of our site with our social media, advertising and analytics partners. See details  IMAGECOLORPICKER.COM ...pick your color online Color Picker Click on the image to get the html codes..  Use the online image color picker right to select a color and get the HTML Color Code of this pixel. Also you get the HEX color code value, RGB value and HSV value. You can put a picture url in the textbox below or upload your own image. (for example an screenshot of your desktop). Or use an website url, you will see a thumbnail on the right side.  HTML/HEX code:\t#f4c4d4\t RGB code:\trgb(244, 196, 212)\t show more Dominant color:    Palette:   Upload your image We think data protection is important! No data is sent. The magic happens in your browser.  - or - Use this box to get the HTML color code from a website. Without installing an Extension.  Take website Use this box to get the HTML color code from a picture via his url:  Take image Scan real-life surfaces to find their digital color values. Scan real-life surfaces to find their digital color values. This website is financed by advertisements. You use a blocker. We understand that you don't want to see advertisements. Operating and maintaining this site costs us money. We are very happy about any support! Donate with PayPal button Love imagecolorpicker.com?  Give our service 5 stars.   Copyright 2020 - ImageColorPicker.com | V: color-picker-244 | Privacy Policy | Imprint"
    },
    "H",
    {
      "c": "#feefd8"
    },
    "J",
    {
      "c": "#ddfdd4"
    },
    "K",
    {
      "c": "#d2ffe8"
    },
    "L",
    {
      "c": "#e9feff"
    },
    ":\n;",
    {
      "c": "#fff1ff"
    },
    "\"\n'",
    {
      "c": "#fcfcfc",
      "w": 2.25
    },
    "Enter"
  ],
  [
    {
      "w": 2.25
    },
    "Shift",
    {
      "c": "#fff1ff"
    },
    "Z",
    {
      "c": "#e9feff"
    },
    "X",
    {
      "c": "#d2ffe8"
    },
    "C",
    {
      "c": "#ddfdd4"
    },
    "V",
    {
      "c": "#feefd8"
    },
    "B",
    "N",
    {
      "c": "#ddfdd4"
    },
    "M",
    {
      "c": "#d2ffe8"
    },
    "<\n,",
    {
      "c": "#e9feff"
    },
    ">\n.",
    {
      "c": "#fff1ff"
    },
    "?\n/",
    {
      "c": "#fcfcfc",
      "w": 2.75
    },
    "Shift"
  ],
  [
    {
      "w": 1.25
    },
    "Ctrl",
    {
      "w": 1.25
    },
    "Win",
    {
      "w": 1.25
    },
    "Alt",
    {
      "c": "#fff1ff",
      "a": 7,
      "w": 6.25
    },
    "",
    {
      "c": "#fcfcfc",
      "a": 4,
      "w": 1.25
    },
    "Alt",
    {
      "w": 1.25
    },
    "Win",
    {
      "w": 1.25
    },
    "Menu",
    {
      "w": 1.25
    },
    "Ctrl"
  ]
]
```

**Comment by Kirpal** [comment]
Looks like you've got a few funky key colors:

> "c": "Got it! We use cookies to...

**Comment by SivertGullbergHansen** [comment]
> Looks like you've got a few funky key colors:
> 
> > "c": "Got it! We use cookies to...
> 
> See the colors for H and Y and a few other places

I see hahaha. Thank you, again.
