### ISSUE TITLE
ReferenceError: StructRNA of type VectorFont has been removed

### ISSUE THREAD

**Issue by alinelena** [Kirpal/Keyboard-Layout-Editor-for-Blender#73]
trying 

```
Python: Traceback (most recent call last):
  File "/home/drFaustroll/.config/blender/2.91/scripts/addons/Keyboard-Layout-Editor-for-Blender/__init__.py", line 30, in execute
    return import_keyboard.load_json(self, self.filepath)
  File "/home/drFaustroll/.config/blender/2.91/scripts/addons/Keyboard-Layout-Editor-for-Blender/src/import_keyboard.py", line 373, in load_json
    read(filepath)
  File "/home/drFaustroll/.config/blender/2.91/scripts/addons/Keyboard-Layout-Editor-for-Blender/src/import_keyboard.py", line 231, in read
    labels.add(
  File "/home/drFaustroll/.config/blender/2.91/scripts/addons/Keyboard-Layout-Editor-for-Blender/src/labels.py", line 208, in add
    curve = add_text(key_label.text, label_size, font, label_position, box)
  File "/home/drFaustroll/.config/blender/2.91/scripts/addons/Keyboard-Layout-Editor-for-Blender/src/labels.py", line 156, in add_text
    new_label.data.font = font
ReferenceError: StructRNA of type VectorFont has been removed

location: <unknown location>:-1

```

attached the keymap

http://www.keyboard-layout-editor.com/#/gists/60d3c7dc61893e1403a3548a93ce08cc
this is using latest release of addon

**Comment by alinelena** [comment]
duplicate needs blender restart
