### ISSUE TITLE
AttributeError: 'MeshEdge' object has no attribute 'crease'

### ISSUE THREAD

**Issue by leifniem** [Kirpal/Keyboard-Layout-Editor-for-Blender#80]
**Required Information**
- Blender version: 4.1
- Add-on version: 3.3
- Link to the layout: [Link](http://www.keyboard-layout-editor.com/##@@_y:0.75&x:17.2%3B&=Rotary%2F%2F%0A%0A%0A%0A%0A%0APgUp%3B&@_y:-0.85&x:3%3B&=%2F@%0A2%3B&@_y:-0.8999999999999999&x:1%3B&=Esc&=!%0A1&_x:9.95%3B&=%2F_%0A-&=+%0A%2F=&_w:2%3B&=Backspace%3B&@_y:-0.25&x:17.45%3B&=PgDn%3B&@_y:-0.75&x:0.75&w:1.5%3B&=Tab&=Q&_x:9.45%3B&=P&=%7B%0A%5B&=%7D%0A%5D&_w:1.5%3B&=%7C%0A%5C%3B&@_y:-0.25&x:17.7%3B&=Delete%3B&@_y:-0.75&x:0.5&w:1.75%3B&=Caps%20Lock&=A&_x:9.95%3B&=%2F:%0A%2F%3B&=%22%0A'&_w:2.25%3B&=Enter%3B&@_x:0.25&w:2.25%3B&=Shift&=Z&_x:9.45%3B&=%3E%0A.&=%3F%0A%2F%2F&=%E2%86%91&_w:2%3B&=Shift%3B&@_x:0.25&w:1.25%3B&=Ctrl&_w:1.25%3B&=Super&_x:11.2%3B&=%E2%86%90&=%E2%86%93&=%E2%86%92%3B&@_r:12&y:-5.85&x:6.3%3B&=%25%0A5%3B&@_y:-1.0000000000000004&x:7.3%3B&=%5E%0A6%3B&@_y:-0.9999999999999996&x:4.3%3B&=%23%0A3&=$%0A4%3B&@_y:-4.440892098500626e-16&x:3.8%3B&=W&=E&=R&=T%3B&@_x:4.05%3B&=S&=D&=F&=G%3B&@_x:4.55%3B&=X&=C&=V&=B%3B&@_x:4.8&w:1.25%3B&=Alt&_w:2.5%3B&=Space%3B&@_r:-12&y:-1.5500000000000003&x:8.25%3B&=%2F&%0A7&=*%0A8&=(%0A9&=)%0A0%3B&@_x:7.75%3B&=Y&=U&=I&=O%3B&@_x:8%3B&=H&=J&=K&=L%3B&@_x:7.5%3B&=B&=N&=M&=%3C%0A,%3B&@_x:7.5&w:2.75%3B&=Space&_w:1.5%3B&=Alt
)

**Describe the bug**
I get the error when trying to import the layout

**Error Trace**
```
Python: Traceback (most recent call last):
  File "C:\Users\Leif\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Keyboard-Layout-Editor-for-Blender\src\import_keyboard.py", line 373, in load_json
    read(filepath)
  File "C:\Users\Leif\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Keyboard-Layout-Editor-for-Blender\src\import_keyboard.py", line 231, in read
    labels.add(
  File "C:\Users\Leif\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Keyboard-Layout-Editor-for-Blender\src\labels.py", line 210, in add
    add_curve(key, curve, label_length, material_name, key_label.size, key_obj, box, offset)
  File "C:\Users\Leif\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Keyboard-Layout-Editor-for-Blender\src\labels.py", line 105, in add_curve
    edge.crease = 1
AttributeError: 'MeshEdge' object has no attribute 'crease'
```

**Comment by leifniem** [comment]
The change causing this is most possibly: https://projects.blender.org/blender/blender/commit/e5ec04d73c7873498f4052cbb9f58acfdaf4b7b0

**Comment by ztlawton** [comment]
@leifniem Do you know of a fix for this?

**Comment by leifniem** [comment]
> @leifniem Do you know of a fix for this?

Sadly not, I haven't tinkered with blender plugins yet.
